// Simple city list for dropdown
export const CITIES = [
  'Karachi',
  'Lahore',
  'Islamabad',
  'Rawalpindi',
  'Faisalabad',
  'Multan',
  'Peshawar',
  'Quetta',
  'Hyderabad',
  'Sialkot',
  'Gujranwala',
  'Bahawalpur',
  'Sargodha',
  'Sukkur',
  'Larkana',
  'Sheikhupura',
  'Rahim Yar Khan',
  'Jhang',
  'Dera Ghazi Khan',
  'Gujrat',
  'Sahiwal',
  'Wah',
  'Mardan',
  'Kasur',
  'Okara',
  'Mingora',
  'Mirpur Khas',
  'Chiniot',
  'Kamoke',
  'Mandi Bahauddin',
  'Jhelum',
  'Khanewal',
  'Hafizabad',
  'Kohat',
  'Jacobabad',
  'Shikarpur',
  'Muzaffargarh',
  'Khanpur',
  'Gojra',
  'Bahawalnagar',
  'Abbottabad',
  'Tando Adam',
  'Turbat',
  'Dera Ismail Khan',
  'Vehari',
  'Nawabshah',
  'Jaranwala',
  'Khairpur',
  'Daska',
  'Chishtian',
  'Dadu',
  'Muridke',
  'Pakpattan',
  'Khuzdar',
  'Wazirabad',
  'Kamber Ali Khan',
  'Tando Allahyar',
  'Ahmadpur East',
  'Vihari',
  'Kot Addu',
  'Nowshera',
  'Swabi',
  'Chakwal',
  'Mianwali',
  'Kandhkot',
  'Hasilpur',
  'Arifwala',
  'Attock',
  'Chaman',
  'Burewala',
  'Mansehra',
  'Lodhran',
  'Charsadda',
  'Tando Muhammad Khan',
  'Haroonabad',
  'Shahdadpur',
  'Shahkot',
  'Mian Channu',
  'Kamalia',
  'Jatoi',
  'Dipalpur',
  'Ghotki',
  'Samundri',
  'Shorkot',
  'Hujra Shah Muqeem',
  'Kabirwala',
  'Matli',
  'Narowal',
  'Kahror Pakka',
  'Karak',
  'Bhalwal',
  'Kundian',
  'Pattoki',
  'Risalpur',
  'Kotri',
  'Jalalpur Jattan',
  'Pindi Bhattian',
  'Jampur',
  'Mianwali Bangla',
  'Toba Tek Singh',
  'Other'
];
// Add major French cities
export const FRENCH_CITIES = [
  'Paris',
  'Marseille',
  'Lyon',
  'Toulouse',
  'Nice',
  'Nantes',
  'Strasbourg',
  'Montpellier',
  'Bordeaux',
  'Lille',
  'Rennes',
  'Reims',
  'Le Havre',
  'Saint-Étienne',
  'Toulon',
  'Grenoble',
  'Dijon',
  'Angers',
  'Nîmes',
  'Villeurbanne',
  'Clermont-Ferrand',
  'Le Mans',
  'Aix-en-Provence',
  'Brest',
  'Tours',
  'Amiens',
  'Limoges',
  'Annecy',
  'Perpignan',
  'Boulogne-Billancourt',
  'Metz',
  'Besançon',
  'Orléans',
  'Rouen',
  'Mulhouse',
  'Caen',
  'Saint-Denis',
  'Argenteuil',
  'Montreuil',
  'Avignon',
  'Poitiers',
  'Asnières-sur-Seine',
  'Versailles',
  'Colombes',
  'Aulnay-sous-Bois',
  'Rueil-Malmaison',
  'Pau',
  'Aubervilliers',
  'Champigny-sur-Marne',
  'La Rochelle',
];

export const ALL_CITIES = [...CITIES, ...FRENCH_CITIES];
